Tsarkov.WeatherProject.Host/Models/CityModel.cs
using System;
using System.Runtime.InteropServices.WindowsRuntime;
using NLog.LayoutRenderers;
using Tsarkov.WeatherProject.Models.DbModels;

namespace Tsarkov.WeatherProject.Models
{
	/// <summary>
	/// Модель города
	/// </summary>
	public class CityModel
	{
		/// <summary>
		/// Идентификатор
		/// </summary>
		public int Id { get; set; }
		
		/// <summary>
		/// Название
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Широта
		/// </summary>
		public double? Latitude { get; set; }

		/// <summary>
		/// Долгота
		/// </summary>
		public double? Longitude { get; set; }

		/// <summary>
		/// Признак присутсвия города в мониторинге
		/// </summary>
		public bool IsMonitored { get; set; }

		/// <summary>
		/// Метод проверки валидности
		/// </summary>
		/// <returns></returns>
		public bool IsValid()
		{
			if (string.IsNullOrWhiteSpace(Name))
			{
				return false;
			}

			if (Latitude == null || Latitude < -90 || Latitude > 90)
			{
				return false;
			}

			if (Longitude == null || Longitude < -180 || Longitude > 180)
			{
				return false;
			}

			return true;
		}

		/// <summary>
		/// Метод преобразования из пользовательской модели города в модель БД
		/// </summary>
		/// <returns></returns>
		public City GetDbCity()
		{
			return new City()
			{
				Latitude = this.Latitude ?? 0,
				Name = this.Name,
				Longitude = this.Longitude ?? 0
			};
		}
	}
}

Tsarkov.WeatherProject.Host/Models/ErrorViewModel.cs
using System;

namespace Tsarkov.WeatherProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tsarkov.WeatherProject.Host/Models/WeatherModel.cs
using System.Collections.Generic;
using Tsarkov.WeatherProject.Models.DbModels;

namespace Tsarkov.WeatherProject.Models
{
	public class WeatherModel
	{
		public City City { get; set; }

		public IList<WeatherInCity> WeaterInCity { get; set; } = new List<WeatherInCity>();
	}
}

Tsarkov.WeatherProject.Host/Controllers/CityController.cs
using System;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Tsarkov.WeatherProject.BL;
using Tsarkov.WeatherProject.DataAccess.Helpers;
using Tsarkov.WeatherProject.Models;
using Tsarkov.WeatherProject.Models.DbModels;

namespace Tsarkov.WeatherProject.Host.Controllers
{
	[Authorize]
	public class CityController : Controller
	{
		private readonly ICityHelper _cityHelper;
		private readonly ICoordinateHelper _coordinateHelper;

		/// <summary>
		/// .ctor
		/// </summary>
		public CityController(ICityHelper cityHelper, ICoordinateHelper coordinateHelper)
		{
			_cityHelper = cityHelper ?? throw new ArgumentNullException(nameof(cityHelper));
			_coordinateHelper = coordinateHelper ?? throw new ArgumentNullException(nameof(coordinateHelper));
		}

		/// <summary>
		/// Метод получения Index View
		/// </summary>
		[HttpGet]
		public IActionResult Index()
		{
			var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
			var monitoredIds = _cityHelper.GetCityIdsMonitored(userId);
			var listCities = _cityHelper.GetCities().Select(c => new CityModel()
			{
				Latitude = c.Latitude,
				Name = c.Name,
				IsMonitored = monitoredIds.Contains(c.Id),
				Longitude = c.Longitude,
				Id = c.Id
			}).ToList();
			return View(listCities);
		}

		/// <summary>
		/// Метод добавления города в БД
		/// </summary>
		[HttpPost]
		public IActionResult Add(CityModel city)
		{
			if (String.IsNullOrWhiteSpace(city.Name))
			{
				return Redirect("Index?status=AddError&reason=Name");
			}

			if (!city.IsValid())
			{
				var coordinates = _coordinateHelper.GetCoordinatesByCityName(city.Name);
				city.Latitude = coordinates.Item1;
				city.Longitude = coordinates.Item2;
				if (!city.IsValid())
				{
					return Redirect("Index?status=AddError&reason=Coordinates");
				}
			}

			_cityHelper.AddCity(city.GetDbCity());
			return Redirect("Index?status=AddSuccess");
		}

		/// <summary>
		/// Метод добавления города в подборку к пользователю
		/// </summary>
		[HttpPost]
		public IActionResult AddToMonitoring(CityByUser weatherInCity)
		{
			var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
			_cityHelper.AddCityToMonitoring(weatherInCity.CityId, userId);
			return Ok();
		}
	}
}

Tsarkov.WeatherProject.Host/Controllers/HomeController.cs
using System.Diagnostics;
using FluentEmail.Core;
using Microsoft.AspNetCore.Mvc;
using NLog;
using Tsarkov.WeatherProject.Models;
using ILogger = NLog.ILogger;

namespace Tsarkov.WeatherProject.Host.Controllers
{
	public class HomeController : Controller
	{
		public HomeController(IFluentEmailFactory factory)
		{
			var email = factory.Create();
			email.Body("asdasd").To("carkov1990@gmail.com").Send();
		}
		
		private static ILogger Logger = LogManager.GetCurrentClassLogger();

		public IActionResult Index()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
		}
	}
}

Tsarkov.WeatherProject.Host/Controllers/WeatherController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Tsarkov.WeatherProject.DataAccess.Helpers;
using Tsarkov.WeatherProject.Models;
using Tsarkov.WeatherProject.Models.DbModels;

namespace Tsarkov.WeatherProject.Host.Controllers
{
	public class WeatherController : Controller
	{
		private readonly ICityHelper _cityHelper;
		private readonly IWeatherHelper _weatherHelper;
		
		/// <summary>
		/// .ctor
		/// </summary>
		public WeatherController(ICityHelper cityHelper, IWeatherHelper weatherHelper)
		{
			_weatherHelper = weatherHelper ?? throw new ArgumentNullException(nameof(weatherHelper));
			_cityHelper = cityHelper ?? throw new ArgumentNullException(nameof(cityHelper));
		}
		
		/// <summary>
		/// Метод получения погоды по городу
		/// </summary>
		[HttpGet]
		public IActionResult Index([FromQuery]int cityId)
		{
			var weatherModel = new WeatherModel();
			var city = _cityHelper.GetCityById(cityId);
			weatherModel.City = city;
			var listWeathers = _weatherHelper.GetWeatherInCities(cityId);
			weatherModel.WeaterInCity = listWeathers;
			return View(weatherModel);
		}
	}
}

Tsarkov.WeatherProject.Host/Views/City/Index.cshtml
@using Tsarkov.WeatherProject.Models.DbModels;
@model IList<CityModel>
@{

    ViewBag.Title = "Список городов";
    Layout = "_Layout";
}


<div class="row">
    <div class="col-md-6">
        <h2>Список городов</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Название города</th>
                <th>Широта</th>
                <th>Долгота</th>
                <th>Добавить в подборку</th>
            </tr>
            </thead>
            <tbody>
            @{
                foreach (var city in Model)
                {
                    <tr>
                        <th scope="row">@city.Id</th>
                        <td><a href="/Weather/Index?cityId=@city.Id">@city.Name</a></td>
                        <td>@city.Latitude</td>
                        <td>@city.Longitude</td>
                        <td>
                            @{
                                if (!city.IsMonitored)
                                {
                                    <button type="button" class="btn btn-success" onclick="addToMonitoring(@city.Id)">+</button>
                                }
                            }
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
</div>
<div></div>

<div class="row">
    <div class="col-md-6">
        <h3>Добавить город</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form asp-action="Add" method="post">
            <div class="form-group">
                <label for="Name">Название города</label>
                <input required="true" type="text" class="form-control" id="Name" name="Name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="Latitude">Широта</label>
                <input type="text" class="form-control" id="Latitude" name="Latitude" placeholder="Latitude">
            </div>
            <div class="form-group">
                <label for="Longitude">Долгота</label>
                <input type="text" class="form-control" id="Longitude" name="Longitude" placeholder="Longitude">
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
</div>

<script>


    function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, '\\$&');
        var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, ' '));
    }

    function addToMonitoring(cityId) {
        var formData = new FormData(document.forms.person);
        formData.append("CityId", cityId);
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "/City/AddToMonitoring");
        xhr.send(formData);
        
        xhr.onreadystatechange = function(target)
        {
            if (xhr.readyState === 4) {
                if (xhr.status === 200) {
                    location.reload();
                } else {
                    alert('Город не добавлен в подборку.');
                }
            }
        }
    }

    var status = getParameterByName("status");
    if (status == 'AddError') {
        var reason = getParameterByName("reason");
        if (reason == 'Coordinates') {
            alert('Город не добавлен. Невозможно определить координаты');
        } else if (reason == 'Name') {
            alert('Город не добавлен. Вы не указали название');
        }

    } else if (status == 'AddSuccess') {
        alert('Город успешно добавлен');
    } else if (status == 'AddMonitoringSuccess') {
        alert('Город успешно добавлен в подборку');
    }

</script>

Tsarkov.WeatherProject.Host/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Tsarkov.WeatherProject.Host/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tsarkov.WeatherProject.Host/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Tsarkov.WeatherProject.Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tsarkov.WeatherProject</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tsarkov.WeatherProject</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="City" asp-action="Index">Cities</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Tsarkov.WeatherProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Tsarkov.WeatherProject.Host/Views/Weather/Index.cshtml
@model WeatherModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Погода в городе</h2>

<h3>@Model.City?.Name</h3>

<div class="row">
    <div class="col-md-6">
        <h3>@Model.WeaterInCity.FirstOrDefault()?.Temperature C</h3>
    </div>
    <div class="col-md-6">
    </div>
</div>

@* <div class="row"> *@
@*     <div class="col-md-4"> *@
@*         <button class="btn btn-primary" onclick="refresh(@Model.City.Id)">Обновить</button> *@
@*     </div> *@
@*     <div class="col-md-4"></div> *@
@*     <div class="col-md-4"></div> *@
@* </div> *@

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Температура</th>
                <th>Время</th>
            </tr>
            </thead>
            <tbody>
            @{
                var i = 0; 
                foreach (var weatherInCity in Model.WeaterInCity)
                {
                    i++;
                    <tr>
                        <th scope="row">@i</th>
                        <td>@weatherInCity.Temperature</td>
                        <td>@weatherInCity.Date</td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
    
</div>